// Hand-curated company names for tickers where Yahoo's longName/shortName is
// garbled, abbreviated, or truncated past the point of being useful. These
// override the algorithmic title-caser in normalizeScannerName(). Most entries
// are sourced from Yahoo `longName` (cleaner than the all-caps `shortName`),
// with light cleanup for casing inconsistencies.
export const SCANNER_NAME_OVERRIDES: Record<string, string> = {
  // CSV-corrupted upstream — full replacements
  "3483.T":    "Takara Leben Real Estate Investment Corporation",
  "036930.KS": "JUSUNG Engineering Co., Ltd.",
  "042700.KQ": "Hanmi Semiconductor Co., Ltd.",
  "259960.KQ": "Krafton, Inc.",

  // KS chaos — canonical names
  "000660.KS": "SK Hynix Inc.",
  "003490.KS": "Korean Air Lines Co., Ltd.",
  "005380.KS": "Hyundai Motor Company",
  "005930.KS": "Samsung Electronics Co., Ltd.",
  "006400.KS": "Samsung SDI Co., Ltd.",
  "008770.KS": "Hotel Shilla Co., Ltd.",
  "012450.KS": "Hanwha Aerospace Co., Ltd.",
  "032830.KS": "Samsung Life Insurance Co., Ltd.",
  "035420.KS": "NAVER Corporation",
  "036570.KS": "NCsoft Corporation",
  "051910.KS": "LG Chem Ltd.",
  "051915.KS": "LG Chem Ltd. (Pref)",
  "056080.KQ": "Yujin Robot Co., Ltd.",
  "066570.KS": "LG Electronics Inc.",
  "088350.KS": "Hanwha Life Insurance Co., Ltd.",
  "207940.KS": "Samsung Biologics Co., Ltd.",
  "277810.KQ": "Rainbow Robotics Inc.",
  "348340.KQ": "Neuromeka Co., Ltd.",
  "373220.KQ": "LG Energy Solution, Ltd.",

  // CN — full names (Yahoo longName, light cleanup of "Co.,Ltd" spacing)
  "000513.SZ": "Livzon Pharmaceutical Group Inc.",
  "000538.SZ": "Yunnan Baiyao Group Co., Ltd.",
  "000792.SZ": "Qinghai Salt Lake Industry Co., Ltd.",
  "000876.SZ": "New Hope Liuhe Co., Ltd.",
  "000988.SZ": "HGTECH Company Limited",
  "000998.SZ": "Yuan Long Ping High-Tech Agriculture Co., Ltd.",
  "002008.SZ": "Han's Laser Technology Industry Group Co., Ltd.",
  "002049.SZ": "Unigroup Guoxin Microelectronics Co., Ltd.",
  "002156.SZ": "Tongfu Microelectronics Co., Ltd.",
  "002230.SZ": "iFLYTEK Co., Ltd.",
  "002236.SZ": "Zhejiang Dahua Technology Co., Ltd.",
  "002371.SZ": "NAURA Technology Group Co., Ltd.",
  "002384.SZ": "Suzhou Dongshan Precision Manufacturing Co., Ltd.",
  "002415.SZ": "Hangzhou Hikvision Digital Technology Co., Ltd.",
  "002475.SZ": "Luxshare Precision Industry Co., Ltd.",
  "002518.SZ": "Shenzhen KSTAR Science and Technology Co., Ltd.",
  "002714.SZ": "Muyuan Foods Co., Ltd.",
  "002851.SZ": "Shenzhen Megmeet Electrical Co., Ltd.",
  "300124.SZ": "Shenzhen Inovance Technology Co., Ltd.",
  "300274.SZ": "Sungrow Power Supply Co., Ltd.",
  "300476.SZ": "Victory Giant Technology (Huizhou) Co., Ltd.",
  "300693.SZ": "Shenzhen Sinexcel Electric Co., Ltd.",
  "300757.SZ": "RoboTechnik Intelligent Technology Co., Ltd.",
  "300760.SZ": "Shenzhen Mindray Bio-Medical Electronics Co., Ltd.",
  "300870.SZ": "Shenzhen Honor Electronic Co., Ltd.",
  "302132.SZ": "AVIC Chengdu Aircraft Company Limited",
  "600085.SS": "Beijing Tongrentang Co., Ltd.",
  "600096.SS": "Yunnan Yuntianhua Co., Ltd.",
  "600276.SS": "Jiangsu Hengrui Pharmaceuticals Co., Ltd.",
  "600438.SS": "Tongwei Co., Ltd.",
  "600584.SS": "JCET Group Co., Ltd.",
  "600598.SS": "Heilongjiang Agriculture Company Limited",
  "600699.SS": "Ningbo Joyson Electronic Corp.",
  "600887.SS": "Inner Mongolia Yili Industrial Group Co., Ltd.",
  "603986.SS": "GigaDevice Semiconductor Inc.",
  "688012.SS": "Advanced Micro-Fabrication Equipment Inc. China",
  "688036.SS": "Shenzhen Transsion Holdings Co., Ltd.",
  "688126.SS": "National Silicon Industry Group Co., Ltd.",
  "688188.SS": "Shanghai BOCHU Electronic Technology Corporation Limited",
  "688195.SS": "Optowide Technologies Co., Ltd.",
  "688256.SS": "Cambricon Technologies Corporation Limited",
  "688363.SS": "Bloomage Biotechnology Corporation Limited",
  "688396.SS": "China Resources Microelectronics Limited",
  "688561.SS": "Qi An Xin Technology Group Inc.",
  "688777.SS": "Supcon Technology Co., Ltd.",
  "688819.SS": "Tianneng Battery Group Co., Ltd.",
  "688981.SS": "Semiconductor Manufacturing International Corporation",

  // HK — full names from Yahoo longName (replaces abbreviated shortName)
  "0013.HK":   "HUTCHMED (China) Limited",
  "0020.HK":   "SenseTime Group Inc.",
  "0027.HK":   "Galaxy Entertainment Group Limited",
  "0038.HK":   "First Tractor Company Limited",
  "0045.HK":   "The Hongkong and Shanghai Hotels, Limited",
  "0100.HK":   "MiniMax Group Inc.",
  "0288.HK":   "WH Group Limited",
  "0293.HK":   "Cathay Pacific Airways Limited",
  "0386.HK":   "China Petroleum & Chemical Corporation",
  "0570.HK":   "China Traditional Chinese Medicine Holdings Co. Limited",
  "0606.HK":   "SCE Intelligent Commercial Management Holdings Limited",
  "0670.HK":   "China Eastern Airlines Corporation Limited",
  "0700.HK":   "Tencent Holdings Limited",
  "0753.HK":   "Air China Limited",
  "0857.HK":   "PetroChina Company Limited",
  "0981.HK":   "Semiconductor Manufacturing International Corporation",
  "1024.HK":   "Kuaishou Technology",
  "1093.HK":   "CSPC Pharmaceutical Group Limited",
  "1128.HK":   "Wynn Macau, Limited",
  "1177.HK":   "Sino Biopharmaceutical Limited",
  "1179.HK":   "H World Group Limited",
  "1211.HK":   "BYD Company Limited",
  "1299.HK":   "AIA Group Limited",
  "1308.HK":   "SITC International Holdings Company Limited",
  "1347.HK":   "Hua Hong Semiconductor Limited",
  "1610.HK":   "COFCO Joycome Foods Limited",
  "1672.HK":   "Ascletis Pharma Inc.",
  "1801.HK":   "Innovent Biologics, Inc.",
  "1877.HK":   "Shanghai Junshi Biosciences Co., Ltd.",
  "1919.HK":   "COSCO SHIPPING Holdings Co., Ltd.",
  "1928.HK":   "Sands China Ltd.",
  "2015.HK":   "Li Auto Inc.",
  "2096.HK":   "Simcere Pharmaceutical Group Limited",
  "2196.HK":   "Shanghai Fosun Pharmaceutical (Group) Co., Ltd.",
  "2257.HK":   "Sirnaomics Ltd.",
  "2269.HK":   "WuXi Biologics (Cayman) Inc.",
  "2282.HK":   "MGM China Holdings Limited",
  "2318.HK":   "Ping An Insurance (Group) Company of China, Ltd.",
  "2319.HK":   "China Mengniu Dairy Company Limited",
  "2359.HK":   "WuXi AppTec Co., Ltd.",
  "2601.HK":   "China Pacific Insurance (Group) Co., Ltd.",
  "2607.HK":   "Shanghai Pharmaceuticals Holding Co., Ltd.",
  "2616.HK":   "CStone Pharmaceuticals",
  "2628.HK":   "China Life Insurance Company Limited",
  "3347.HK":   "Hangzhou Tigermed Consulting Co., Ltd.",
  "3692.HK":   "Hansoh Pharmaceutical Group Company Limited",
  "3750.HK":   "Contemporary Amperex Technology Co., Limited",
  "3759.HK":   "Pharmaron Beijing Co., Ltd.",
  "6160.HK":   "BeOne Medicines AG",
  "6821.HK":   "Asymchem Laboratories (Tianjin) Co., Ltd.",
  "6883.HK":   "Eternal Beauty Holdings Limited",
  "9626.HK":   "Bilibili Inc.",
  "9660.HK":   "Horizon Robotics",
  "9688.HK":   "Zai Lab Limited",
  "9863.HK":   "Zhejiang Leapmotor Technology Co., Ltd.",
  "9866.HK":   "NIO Inc.",
  "9868.HK":   "XPeng Inc.",
  "9880.HK":   "UBTECH Robotics Corp Ltd",
  "9926.HK":   "Akeso, Inc.",
  "9961.HK":   "Trip.com Group Limited",
  "9988.HK":   "Alibaba Group Holding Limited",

  // JP — full names
  "3350.T":    "Metaplanet Inc.",
  "3352.T":    "Buffalo Co., Ltd.",
  "4063.T":    "Shin-Etsu Chemical Co., Ltd.",
  "4502.T":    "Takeda Pharmaceutical Company Limited",
  "4503.T":    "Astellas Pharma Inc.",
  "4519.T":    "Chugai Pharmaceutical Co., Ltd.",
  "4565.T":    "Nxera Pharma Co., Ltd.",
  "4568.T":    "Daiichi Sankyo Company, Limited",
  "4578.T":    "Otsuka Holdings Co., Ltd.",
  "4587.T":    "PeptiDream Inc.",
  "4592.T":    "SanBio Company Limited",
  "4661.T":    "Oriental Land Co., Ltd.",
  "5713.T":    "Sumitomo Metal Mining Co., Ltd.",
  "6302.T":    "Sumitomo Heavy Industries, Ltd.",
  "6501.T":    "Hitachi, Ltd.",
  "6702.T":    "Fujitsu Limited",
  "6861.T":    "Keyence Corporation",
  "6954.T":    "Fanuc Corporation",
  "7203.T":    "Toyota Motor Corporation",
  "7735.T":    "SCREEN Holdings Co., Ltd.",
  "7974.T":    "Nintendo Co., Ltd.",
  "8001.T":    "ITOCHU Corporation",
  "8002.T":    "Marubeni Corporation",
  "8031.T":    "Mitsui & Co., Ltd.",
  "8035.T":    "Tokyo Electron Limited",
  "8053.T":    "Sumitomo Corporation",
  "8058.T":    "Mitsubishi Corporation",
  "8306.T":    "Mitsubishi UFJ Financial Group, Inc.",
  "8316.T":    "Sumitomo Mitsui Financial Group, Inc.",
  "8411.T":    "Mizuho Financial Group, Inc.",
  "8630.T":    "Sompo Holdings, Inc.",
  "8725.T":    "MS&AD Insurance Group Holdings, Inc.",
  "8766.T":    "Tokio Marine Holdings, Inc.",
  "9201.T":    "Japan Airlines Co., Ltd.",
  "9202.T":    "ANA Holdings Inc.",
  "9433.T":    "KDDI Corporation",
  "9682.T":    "DTS Corporation",
  "9697.T":    "Capcom Co., Ltd.",

  // SGX — full names from Yahoo longName (replaces abbreviated shortName)
  "5E2.SI":    "Seatrium Limited",
  "BN4.SI":    "Keppel Ltd.",
  "C6L.SI":    "Singapore Airlines Limited",
  "D05.SI":    "DBS Group Holdings Ltd.",
  "D5IU.SI":   "Landmark REIT",
  "E5H.SI":    "Golden Agri-Resources Ltd.",
  "F34.SI":    "Wilmar International Limited",
  "F9D.SI":    "Boustead Singapore Limited",
  "G07.SI":    "Great Eastern Holdings Limited",
  "G13.SI":    "Genting Singapore Limited",
  "N2IU.SI":   "Mapletree Pan Asia Commercial Trust",
  "Q0F.SI":    "IHH Healthcare Berhad",
  "VC2.SI":    "Olam Group Limited",
  "Z74.SI":    "Singapore Telecommunications Limited",

  // US-listed foreign tickers — full names from Yahoo longName
  "2330.TW":   "Taiwan Semiconductor Manufacturing Company Limited",
  "4971.TWO":  "IntelliEpi Inc. (Cayman)",
  "AIR.PA":    "Airbus SE",
  "ALV.DE":    "Allianz SE",
  "AMX":       "América Móvil, S.A.B. de C.V.",
  "ANTO.L":    "Antofagasta plc",
  "GBOOY":     "Grupo Financiero Banorte, S.A.B. de C.V.",
  "GEBN.SW":   "Geberit AG",
  "HNR1.DE":   "Hannover Rück SE",
  "IHG.L":     "InterContinental Hotels Group plc",
  "ITUB":      "Itaú Unibanco Holding S.A.",
  "JKS":       "JinkoSolar Holding Co., Ltd.",
  "KOF":       "Coca-Cola FEMSA, S.A.B. de C.V.",
  "LVMUY":     "LVMH Moët Hennessy - Louis Vuitton, Société Européenne",
  "MUV2.DE":   "Münchener Rückversicherungs-Gesellschaft AG",
  "PBR":       "Petróleo Brasileiro S.A. - Petrobras",
  "RHM.DE":    "Rheinmetall AG",
  "RR.L":      "Rolls-Royce Holdings plc",
  "SAF.PA":    "Safran SA",
  "SQM":       "Sociedad Química y Minera de Chile S.A.",
  "TCS.NS":    "Tata Consultancy Services Limited",
  "TSM":       "Taiwan Semiconductor Manufacturing Company Limited",

  // Indonesian tickers — "PT" prefix is the legal convention; "Tbk" = Terbuka
  "ANTM.JK":   "PT Antam (Persero) Tbk",
  "BRPT.JK":   "PT Barito Pacific Tbk",
  "ERAA.JK":   "PT Erajaya Swasembada Tbk",
  "HMSP.JK":   "PT Hanjaya Mandala Sampoerna Tbk",
  "INCO.JK":   "PT Vale Indonesia Tbk",
  "MDKA.JK":   "PT Merdeka Copper Gold Tbk",
  "NIKL.JK":   "PT Pelat Timah Nusantara Tbk",
  "PTRO.JK":   "PT Petrosea Tbk",
  "SMSM.JK":   "PT Selamat Sempurna Tbk",
  "TPIA.JK":   "PT Chandra Asri Pacific Tbk",

  // SGX brand acronyms with generic-word collisions ("ST", "DC")
  "S63.SI":    "ST Engineering Ltd.",
  "AJBU.SI":   "Keppel DC REIT",
  "P40U.SI":   "Starhill Global REIT",

  // US — truncations / shortName artifacts that need cleanup
  "3529.TWO":  "eMemory Technology Inc.",
  "AIG":       "American International Group, Inc.",
  "AMT":       "American Tower Corporation",
  "ASML":      "ASML Holding N.V.",
  "AWK":       "American Water Works Company, Inc.",
  "BA":        "The Boeing Company",
  "BKNG":      "Booking Holdings Inc.",
  "BRK-B":     "Berkshire Hathaway Inc.",
  "CEG":       "Constellation Energy Corporation",
  "CGEH":      "Capstone Green Energy Holdings, Inc.",
  "CMPS":      "COMPASS Pathways plc",
  "DNN":       "Denison Mines Corp.",
  "ETN":       "Eaton Corporation plc",
  "FCX":       "Freeport-McMoRan Inc.",
  "GHRS":      "GH Research plc",
  "HDFCBANK.NS": "HDFC Bank Limited",
  "HRMY":      "Harmony Biosciences Holdings, Inc.",
  "IRDM":      "Iridium Communications Inc.",
  "IRM":       "Iron Mountain Incorporated",
  "MOS":       "The Mosaic Company",
  "MSTR":      "Strategy Inc.",
  "NCLH":      "Norwegian Cruise Line Holdings Ltd.",
  "NUMI.TO":   "Numinus Wellness Inc.",
  "ONC":       "BeOne Medicines AG",
  "SGMO":      "Sangamo Therapeutics, Inc.",
  "PEG":       "Public Service Enterprise Group Incorporated",
  "PGR":       "The Progressive Corporation",
  "RELIANCE.NS": "Reliance Industries Limited",
  "TECK":      "Teck Resources Limited",
  "TEVA":      "Teva Pharmaceutical Industries Limited",
  "TTWO":      "Take-Two Interactive Software, Inc.",
  "URG":       "Ur-Energy Inc.",
  "UUUU":      "Energy Fuels Inc.",
  "VRTX":      "Vertex Pharmaceuticals Incorporated",
  "WMMVY":     "Wal-Mart de México, S.A.B. de C.V.",
  "XNDU":      "Xanadu Quantum Technologies Limited",
  "ZURVY":     "Zurich Insurance Group AG",
};
