import { createClient } from "@libsql/client";
import * as dotenv from "dotenv";

dotenv.config({ path: ".env.local" });

const db = createClient({
  url: process.env.TURSO_DATABASE_URL!,
  authToken: process.env.TURSO_AUTH_TOKEN,
});

const descriptions: Record<string, string> = {
  "000513.SZ": "Chinese pharmaceutical company, modern drugs and TCM formulations.",
  "000538.SZ": "Iconic Chinese TCM brand, known for Yunnan Baiyao hemostatic products.",
  "000792.SZ": "Potash and lithium producer from Qinghai salt Lake deposits.",
  "000876.SZ": "China's largest animal feed and agribusiness conglomerate.",
  "000988.SZ": "Laser technology and optoelectronics manufacturer.",
  "000998.SZ": "Seed and crop science company, named after father of hybrid rice.",
  "002008.SZ": "Industrial laser equipment and automation systems.",
  "002049.SZ": "Smart card and security chip design, Tsinghua Unigroup subsidiary.",
  "002156.SZ": "IC packaging and testing services (OSAT).",
  "002230.SZ": "Chinese AI and speech recognition technology leader.",
  "002236.SZ": "Video surveillance and smart IoT solutions provider.",
  "002371.SZ": "Semiconductor processing equipment for IC manufacturing.",
  "002384.SZ": "Precision manufacturing, FPC, and optoelectronic components.",
  "002415.SZ": "World's largest video surveillance equipment maker.",
  "002475.SZ": "Electronics connector and cable assembly supplier to Apple.",
  "002518.SZ": "UPS power supply and energy storage systems.",
  "002714.SZ": "China's largest pig farming and pork producer.",
  "002851.SZ": "Power electronics, EV chargers, and switched-mode power supplies.",
  "300124.SZ": "Industrial automation, servo drives, and PLC systems.",
  "300274.SZ": "Solar inverters and energy storage systems, global top 3.",
  "300476.SZ": "PCB manufacturing for consumer electronics and automotive.",
  "300693.SZ": "Power quality solutions and energy storage systems.",
  "300757.SZ": "Lab automation and robotic sample handling equipment.",
  "300760.SZ": "Medical devices, patient monitoring, and in-vitro diagnostics.",
  "300870.SZ": "Switching power supplies and power adapters.",
  "302132.SZ": "Military aircraft manufacturer (J-20, J-10), AVIC subsidiary.",
  "600085.SS": "Renowned TCM brand, over 350 years of herbal medicine heritage.",
  "600096.SS": "Fertilizer and chemical materials producer.",
  "600276.SS": "China's largest pharma company, oncology and anesthesia drugs.",
  "600298.SS": "World's largest yeast manufacturer.",
  "600438.SS": "Solar polysilicon and aquaculture (fish farming) conglomerate.",
  "600584.SS": "IC packaging and testing services (OSAT).",
  "600598.SS": "Large-scale farming and agricultural products in Northeast China.",
  "600699.SS": "Automotive safety electronics and intelligent driving systems.",
  "600887.SS": "China's largest dairy company.",
  "603986.SS": "Flash memory and MCU chip design.",
  "688012.SS": "Advanced semiconductor lithography and micro-fabrication equipment.",
  "688036.SS": "Africa's top smartphone brand (Tecno, Infinix, itel).",
  "688126.SS": "Silicon wafer manufacturing for semiconductors.",
  "688188.SS": "CNC press brake and laser cutting systems.",
  "688195.SS": "Optical fiber and fiber laser components.",
  "688256.SS": "Chinese AI chip design, cloud and edge inference processors.",
  "688363.SS": "Hyaluronic acid and biomaterials for medical and cosmetic use.",
  "688396.SS": "Power semiconductors and smart sensors.",
  "688561.SS": "Cybersecurity products, endpoint and cloud protection.",
  "688777.SS": "Industrial automation and process control systems.",
  "688819.SS": "Lead-acid and lithium battery manufacturer.",
  "688981.SS": "China's leading semiconductor foundry (SMIC).",
  "0013.HK": "Biopharma focused on cancer and immunology treatments.",
  "0020.HK": "Chinese AI computer vision and deep learning platform.",
  "0027.HK": "Macau casino and integrated resort operator.",
  "0038.HK": "Agricultural tractor and farm equipment manufacturer.",
  "0045.HK": "Hong Kong luxury hotel operator (Peninsula Hotels).",
  "0100.HK": "Chinese AI company, large language models and video generation.",
  "0288.HK": "World's largest pork producer, owns Smithfield Foods.",
  "0293.HK": "Hong Kong's flag carrier airline.",
  "0386.HK": "China's largest oil refiner and petrochemical producer.",
  "0570.HK": "Traditional Chinese medicine products and health supplements.",
  "0606.HK": "China State Construction, engineering and infrastructure.",
  "0670.HK": "Major Chinese airline, Eastern China route network.",
  "0700.HK": "China's largest internet conglomerate: WeChat, gaming, cloud, fintech.",
  "0753.HK": "China's flag carrier airline.",
  "0857.HK": "China's largest oil and gas producer.",
  "0981.HK": "China's leading semiconductor foundry.",
  "1024.HK": "Short video and livestreaming e-commerce platform.",
  "1093.HK": "Chinese pharmaceutical company, CNS and oncology drugs.",
  "1128.HK": "Luxury casino and resort operator in Macau.",
  "1177.HK": "Chinese biopharma, hepatology and respiratory drugs.",
  "1179.HK": "Budget and mid-scale hotel chain operator in China.",
  "1211.HK": "EV and battery maker, world's largest NEV manufacturer.",
  "1299.HK": "Asia's largest life insurance company.",
  "1308.HK": "Shipping and logistics container services.",
  "1347.HK": "Semiconductor foundry, specialty process technologies.",
  "1610.HK": "Food and beverage products, COFCO subsidiary.",
  "1672.HK": "Biotech focused on liver disease and antiviral drugs.",
  "1801.HK": "Biopharma company, oncology antibody drug development.",
  "1877.HK": "Biotech, first domestic PD-1 antibody (Toripalimab).",
  "1919.HK": "Global shipping and container logistics company.",
  "1928.HK": "Macau casino and integrated resort operator (Venetian, Sands).",
  "2015.HK": "Chinese EV maker, extended-range electric SUVs and sedans.",
  "2096.HK": "Pharmaceutical company, CNS and oncology specialty drugs.",
  "2196.HK": "Diversified pharmaceutical and healthcare company.",
  "2257.HK": "RNAi therapeutics for oncology and fibrosis.",
  "2269.HK": "Biologics CDMO, vaccine and antibody manufacturing.",
  "2282.HK": "Macau casino resort operator (MGM Grand).",
  "2318.HK": "China's largest insurance and fintech conglomerate.",
  "2319.HK": "Major Chinese dairy products company.",
  "2359.HK": "Global CRDMO, drug R&D and manufacturing services.",
  "2601.HK": "China Pacific Insurance, life and P&C insurance.",
  "2607.HK": "Pharmaceutical distributor and retailer.",
  "2616.HK": "Biotech, immuno-oncology drug development.",
  "2628.HK": "China's largest life insurance company.",
  "3347.HK": "Clinical CRO, drug development and trial services.",
  "3692.HK": "Pharmaceutical company, CNS and oncology drugs.",
  "3750.HK": "World's largest EV battery manufacturer.",
  "3759.HK": "Preclinical and clinical CRO/CDMO services.",
  "6160.HK": "Global biotech, oncology drug development and commercialization.",
  "6821.HK": "CDMO, small molecule drug manufacturing services.",
  "6883.HK": "Beauty and skincare products company.",
  "9626.HK": "Video platform, anime, gaming, and youth community.",
  "9660.HK": "AI chip company, automotive intelligent computing solutions.",
  "9688.HK": "Biopharma, oncology and autoimmune drug development.",
  "9863.HK": "Chinese EV maker, smart electric vehicles with Stellantis partnership.",
  "9866.HK": "Premium Chinese EV maker, battery swap technology.",
  "9868.HK": "Chinese smart EV maker, ADAS and autonomous driving tech.",
  "9880.HK": "Humanoid robot and AI education company.",
  "9926.HK": "Biotech, bispecific antibody drug development.",
  "9961.HK": "Online travel agency (Ctrip/Trip.com).",
  "9988.HK": "China's largest e-commerce and cloud platform (Alibaba).",
  "3350.T": "Bitcoin treasury strategy company, Japan's corporate crypto adopter.",
  "3352.T": "Computer peripherals and networking equipment manufacturer.",
};

async function main() {
  let updated = 0;
  for (const [ticker, desc] of Object.entries(descriptions)) {
    const result = await db.execute({
      sql: "UPDATE watchlist_scores SET description = ? WHERE ticker = ?",
      args: [desc, ticker],
    });
    if (result.rowsAffected > 0) updated++;
  }
  console.log("Updated " + updated + " tickers with descriptions (batch 1).");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
