import { createClient } from "@libsql/client";
import * as dotenv from "dotenv";

dotenv.config({ path: ".env.local" });

const db = createClient({
  url: process.env.TURSO_DATABASE_URL!,
  authToken: process.env.TURSO_AUTH_TOKEN,
});

const descriptions: Record<string, string> = {
  "000513.SZ": "Chinese pharmaceutical company, modern drugs and TCM formulations.",
  "000538.SZ": "Iconic Chinese TCM brand, known for Yunnan Baiyao hemostatic products.",
  "000792.SZ": "Potash and lithium producer from Qinghai salt Lake deposits.",
  "000876.SZ": "China's largest animal feed and agribusiness conglomerate.",
  "000988.SZ": "Laser technology and optoelectronics manufacturer.",
  "000998.SZ": "Seed and crop science company, named after father of hybrid rice.",
  "002008.SZ": "Industrial laser equipment and automation systems.",
  "002049.SZ": "Smart card and security chip design, Tsinghua Unigroup subsidiary.",
  "002156.SZ": "IC packaging and testing services (OSAT).",
  "002230.SZ": "Chinese AI and speech recognition technology leader.",
  "002236.SZ": "Video surveillance and smart IoT solutions provider.",
  "002371.SZ": "Semiconductor processing equipment for IC manufacturing.",
  "002384.SZ": "Precision manufacturing, FPC, and optoelectronic components.",
  "002415.SZ": "World's largest video surveillance equipment maker.",
  "002475.SZ": "Electronics connector and cable assembly supplier to Apple.",
  "002518.SZ": "UPS power supply and energy storage systems.",
  "002714.SZ": "China's largest pig farming and pork producer.",
  "002851.SZ": "Power electronics, EV chargers, and switched-mode power supplies.",
  "300124.SZ": "Industrial automation, servo drives, and PLC systems.",
  "300274.SZ": "Solar inverters and energy storage systems, global top 3.",
  "300476.SZ": "PCB manufacturing for consumer electronics and automotive.",
  "300693.SZ": "Power quality solutions and energy storage systems.",
  "300757.SZ": "Lab automation and robotic sample handling equipment.",
  "300760.SZ": "Medical devices, patient monitoring, and in-vitro diagnostics.",
  "300870.SZ": "Switching power supplies and power adapters.",
  "302132.SZ": "Military aircraft manufacturer (J-20, J-10), AVIC subsidiary.",
  "600085.SS": "Renowned TCM brand, over 350 years of herbal medicine heritage.",
  "600096.SS": "Fertilizer and chemical materials producer.",
  "600276.SS": "China's largest pharma company, oncology and anesthesia drugs.",
  "600298.SS": "World's largest yeast manufacturer.",
  "600438.SS": "Solar polysilicon and aquaculture (fish farming) conglomerate.",
  "600584.SS": "IC packaging and testing services (OSAT).",
  "600598.SS": "Large-scale farming and agricultural products in Northeast China.",
  "600699.SS": "Automotive safety electronics and intelligent driving systems.",
  "600887.SS": "China's largest dairy company.",
  "603986.SS": "Flash memory and MCU chip design.",
  "688012.SS": "Advanced semiconductor lithography and micro-fabrication equipment.",
  "688036.SS": "Africa's top smartphone brand (Tecno, Infinix, itel).",
  "688126.SS": "Silicon wafer manufacturing for semiconductors.",
  "688188.SS": "CNC press brake and laser cutting systems.",
  "688195.SS": "Optical fiber and fiber laser components.",
  "688256.SS": "Chinese AI chip design, cloud and edge inference processors.",
  "688363.SS": "Hyaluronic acid and biomaterials for medical and cosmetic use.",
  "688396.SS": "Power semiconductors and smart sensors.",
  "688561.SS": "Cybersecurity products, endpoint and cloud protection.",
  "688777.SS": "Industrial automation and process control systems.",
  "688819.SS": "Lead-acid and lithium battery manufacturer.",
  "688981.SS": "China's leading semiconductor foundry (SMIC).",
  "0013.HK": "Biopharma focused on cancer and immunology treatments.",
  "0020.HK": "Chinese AI computer vision and deep learning platform.",
  "0027.HK": "Macau casino and integrated resort operator.",
  "0038.HK": "Agricultural tractor and farm equipment manufacturer.",
  "0045.HK": "Hong Kong luxury hotel operator (Peninsula Hotels).",
  "0100.HK": "Chinese AI company, large language models and video generation.",
  "0288.HK": "World's largest pork producer, owns Smithfield Foods.",
  "0293.HK": "Hong Kong's flag carrier airline.",
  "0386.HK": "China's largest oil refiner and petrochemical producer.",
  "0570.HK": "Traditional Chinese medicine products and health supplements.",
  "0606.HK": "China State Construction, engineering and infrastructure.",
  "0670.HK": "Major Chinese airline, Eastern China route network.",
  "0700.HK": "China's largest internet conglomerate: WeChat, gaming, cloud, fintech.",
  "0753.HK": "China's flag carrier airline.",
  "0857.HK": "China's largest oil and gas producer.",
  "0981.HK": "China's leading semiconductor foundry.",
  "1024.HK": "Short video and livestreaming e-commerce platform.",
  "1093.HK": "Chinese pharmaceutical company, CNS and oncology drugs.",
  "1128.HK": "Luxury casino and resort operator in Macau.",
  "1177.HK": "Chinese biopharma, hepatology and respiratory drugs.",
  "1179.HK": "Budget and mid-scale hotel chain operator in China.",
  "1211.HK": "EV and battery maker, world's largest NEV manufacturer.",
  "1299.HK": "Asia's largest life insurance company.",
  "1308.HK": "Shipping and logistics container services.",
  "1347.HK": "Semiconductor foundry, specialty process technologies.",
  "1610.HK": "Food and beverage products, COFCO subsidiary.",
  "1672.HK": "Biotech focused on liver disease and antiviral drugs.",
  "1801.HK": "Biopharma company, oncology antibody drug development.",
  "1877.HK": "Biotech, first domestic PD-1 antibody (Toripalimab).",
  "1919.HK": "Global shipping and container logistics company.",
  "1928.HK": "Macau casino and integrated resort operator (Venetian, Sands).",
  "2015.HK": "Chinese EV maker, extended-range electric SUVs and sedans.",
  "2096.HK": "Pharmaceutical company, CNS and oncology specialty drugs.",
  "2196.HK": "Diversified pharmaceutical and healthcare company.",
  "2257.HK": "RNAi therapeutics for oncology and fibrosis.",
  "2269.HK": "Biologics CDMO, vaccine and antibody manufacturing.",
  "2282.HK": "Macau casino resort operator (MGM Grand).",
  "2318.HK": "China's largest insurance and fintech conglomerate.",
  "2319.HK": "Major Chinese dairy products company.",
  "2359.HK": "Global CRDMO, drug R&D and manufacturing services.",
  "2601.HK": "China Pacific Insurance, life and P&C insurance.",
  "2607.HK": "Pharmaceutical distributor and retailer.",
  "2616.HK": "Biotech, immuno-oncology drug development.",
  "2628.HK": "China's largest life insurance company.",
  "3347.HK": "Clinical CRO, drug development and trial services.",
  "3692.HK": "Pharmaceutical company, CNS and oncology drugs.",
  "3750.HK": "World's largest EV battery manufacturer.",
  "3759.HK": "Preclinical and clinical CRO/CDMO services.",
  "6160.HK": "Global biotech, oncology drug development and commercialization.",
  "6821.HK": "CDMO, small molecule drug manufacturing services.",
  "6883.HK": "Beauty and skincare products company.",
  "9626.HK": "Video platform, anime, gaming, and youth community.",
  "9660.HK": "AI chip company, automotive intelligent computing solutions.",
  "9688.HK": "Biopharma, oncology and autoimmune drug development.",
  "9863.HK": "Chinese EV maker, smart electric vehicles with Stellantis partnership.",
  "9866.HK": "Premium Chinese EV maker, battery swap technology.",
  "9868.HK": "Chinese smart EV maker, ADAS and autonomous driving tech.",
  "9880.HK": "Humanoid robot and AI education company.",
  "9926.HK": "Biotech, bispecific antibody drug development.",
  "9961.HK": "Online travel agency (Ctrip/Trip.com).",
  "9988.HK": "China's largest e-commerce and cloud platform (Alibaba).",
  "3350.T": "Bitcoin treasury strategy company, Japan's corporate crypto adopter.",
  "3352.T": "Computer peripherals and networking equipment manufacturer.",
  "3483.T": "Japanese listed company on Tokyo Stock Exchange.",
  "4063.T": "Chemical company, world's largest silicon wafer and PVC producer.",
  "4502.T": "Japan's largest pharmaceutical company with global operations.",
  "4503.T": "Japanese pharmaceutical company, oncology and urology drugs.",
  "4519.T": "Japanese biotech (Roche subsidiary), antibody drug innovation.",
  "4565.T": "Japanese biotech, CNS and neurology drug development.",
  "4568.T": "Japanese pharma, oncology (Enhertu with AstraZeneca partnership).",
  "4578.T": "Japanese pharmaceutical company, CNS and cardiovascular drugs.",
  "4587.T": "Peptide drug discovery platform and therapeutics.",
  "4592.T": "Regenerative medicine and stem cell therapy development.",
  "4661.T": "Operator of Tokyo Disney Resort theme parks.",
  "5713.T": "Non-ferrous metals mining, copper, nickel, and gold.",
  "6108.T": "Japanese listed company on Tokyo Stock Exchange.",
  "6302.T": "Industrial machinery, semiconductor and precision equipment.",
  "6501.T": "Japanese industrial conglomerate, IT, energy, and infrastructure.",
  "6702.T": "Japanese IT services, computing, and digital transformation.",
  "6861.T": "Factory automation sensors and measurement equipment, high margins.",
  "6954.T": "Industrial robots, CNC systems, and factory automation leader.",
  "7203.T": "World's largest automaker, hybrid and hydrogen vehicle leader.",
  "7735.T": "Semiconductor cleaning and coating equipment manufacturer.",
  "7974.T": "Japanese gaming giant, creator of Mario, Zelda, and Switch.",
  "8001.T": "Japanese trading house (sogo shosha), diversified global investments.",
  "8002.T": "Japanese trading house, diversified investments and commodities.",
  "8031.T": "Japanese trading house, global resources, energy, and finance.",
  "8035.T": "Semiconductor manufacturing equipment global leader.",
  "8053.T": "Japanese trading house, mineral resources and infrastructure.",
  "8058.T": "Japan's largest trading house, diversified global conglomerate.",
  "8306.T": "Japan's largest bank and financial services group.",
  "8316.T": "Japan's second-largest banking and financial services group.",
  "8411.T": "Major Japanese banking and financial services group.",
  "8630.T": "Japanese property and casualty insurance company.",
  "8634.T": "Japanese financial services company listed on TSE.",
  "8725.T": "Japanese insurance holding company, P&C and life insurance.",
  "8766.T": "Japan's largest property and casualty insurance company.",
  "9109.T": "Japanese maritime and shipping services company.",
  "9201.T": "Japan's flag carrier airline.",
  "9202.T": "Japan's largest airline group (ANA).",
  "9433.T": "Japanese telecom operator, mobile and broadband (au brand).",
  "9682.T": "IT services, system integration, and consulting.",
  "9697.T": "Video game developer (Street Fighter, Resident Evil, Monster Hunter).",
  "9783.T": "Japanese listed company on Tokyo Stock Exchange.",
  "000660.KS": "World's second-largest memory chip maker (DRAM, NAND).",
  "003490.KS": "Korean Air Lines, South Korea's flag carrier airline.",
  "005380.KS": "South Korea's largest automaker (Hyundai Motor Group).",
  "005930.KS": "World's largest memory chip and smartphone maker.",
  "006400.KS": "Battery manufacturer, EV and energy storage systems.",
  "008770.KS": "Hotel Shilla, duty-free retail and hotel operations.",
  "012450.KS": "Aerospace and defense, satellite and missile systems.",
  "032830.KS": "South Korea's largest life insurance company.",
  "035420.KS": "South Korea's leading search engine and internet platform.",
  "036570.KS": "Online and mobile gaming company (Lineage, Aion).",
  "036930.KS": "Korean listed company on KOSPI.",
  "042700.KQ": "Korean listed company on KOSDAQ.",
  "051910.KS": "Chemicals, EV batteries, and advanced materials.",
  "051915.KS": "LG Chem preferred shares.",
  "056080.KQ": "Robot and automated guided vehicle (AGV) manufacturer.",
  "066570.KS": "Consumer electronics, TVs, home appliances, and EV components.",
  "088350.KS": "South Korean life insurance and financial services.",
  "207940.KS": "Biologics CDMO, antibody drug contract manufacturing.",
  "259960.KQ": "Korean listed company on KOSDAQ.",
  "277810.KQ": "Humanoid and collaborative robot manufacturer.",
  "348340.KQ": "Industrial robotics and factory automation systems.",
  "373220.KQ": "Korean listed company on KOSDAQ.",
  "5E2.SI": "Offshore marine engineering (formerly Sembcorp Marine).",
  "AJBU.SI": "Data center REIT across Asia-Pacific.",
  "BN4.SI": "Diversified conglomerate, offshore energy and property development.",
  "C6L.SI": "Singapore Airlines, Singapore's flag carrier.",
  "C7BU.SI": "Singapore-listed company on SGX.",
  "D05.SI": "Southeast Asia's largest bank.",
  "D5IU.SI": "Singapore REIT, retail and commercial properties.",
  "E5H.SI": "Palm oil plantation company, one of the world's largest.",
  "F34.SI": "Agribusiness, palm oil and food processing conglomerate.",
  "F9D.SI": "Engineering and geospatial technology services.",
  "G07.SI": "Insurance company, Southeast Asia's largest life insurer.",
  "G13.SI": "Gaming and hospitality (Resorts World Sentosa).",
  "N2IU.SI": "Pan-Asia commercial REIT, office and retail properties.",
  "P40U.SI": "Retail and hospitality REIT across Asia.",
  "Q0F.SI": "Healthcare, hospital operator (Parkway, Gleneagles, Acibadem).",
  "S63.SI": "Defense, aerospace, and smart city technology.",
  "T68U.SI": "Singapore-listed REIT on SGX.",
  "VC2.SI": "Agricultural commodity trading and food ingredients.",
  "Z74.SI": "Singapore's largest telecom operator.",
  "2330.TW": "World's largest semiconductor foundry (TSMC).",
  "3529.TWO": "Memory IP and security technology for semiconductors.",
  "4971.TWO": "EPI wafer and semiconductor materials.",
  "500325.NS": "Indian listed company on NSE (numeric ticker code).",
  "532500.NS": "Indian listed company on NSE (numeric ticker code).",
  "HDFCBANK.NS": "India's largest private sector bank.",
  "HINDUNILVR.NS": "Indian FMCG giant, subsidiary of Unilever.",
  "ICICIBANK.NS": "Major Indian private sector bank.",
  "LT.NS": "Indian engineering, construction, and defense conglomerate.",
  "RELIANCE.NS": "India's largest conglomerate: energy, retail, telecom.",
  "SBIN.NS": "State Bank of India, largest government-owned bank.",
  "TATAMOTORS.NS": "India's largest automaker, owns Jaguar Land Rover.",
  "TCS.NS": "India's largest IT services company (Tata Consultancy).",
  "ANTM.JK": "Indonesian state-owned mining, nickel and precious metals.",
  "BRPT.JK": "Indonesian conglomerate, petrochemicals and energy.",
  "ERAA.JK": "Indonesian mobile device distributor and retailer.",
  "HMSP.JK": "Indonesian tobacco company, Philip Morris subsidiary.",
  "INCO.JK": "Indonesian nickel mining company.",
  "MDKA.JK": "Indonesian mining, copper and gold exploration.",
  "NIKL.JK": "Indonesian tin smelting and processing company.",
  "PTRO.JK": "Indonesian mining services and civil construction.",
  "SMSM.JK": "Indonesian automotive parts, filters and components.",
  "TPIA.JK": "Indonesian petrochemical company, olefins and polyethylene.",
  "ABEV": "Latin America's largest brewer (Ambev/AB InBev subsidiary).",
  "ABNB": "Global online marketplace for short-term lodging and experiences.",
  "ADM": "Global agricultural processing and commodity trading.",
  "ADYEY": "European payment processor, global fintech platform.",
  "AFL": "Supplemental insurance, cancer and life policies.",
  "AFRM": "Buy-now-pay-later fintech platform.",
  "AGCO": "Agricultural equipment manufacturer (tractors, combines).",
  "AIG": "Global insurance company, property and casualty.",
  "ALLG": "Allegro MicroSystems, power and sensor ICs for automotive.",
  "ALV.DE": "Global insurance and asset management giant.",
  "AMT": "Cell tower REIT, wireless infrastructure landlord globally.",
  "AMX": "Latin America's largest telecom operator.",
  "ANTO.L": "Chilean copper mining company listed in London.",
  "ASML": "EUV lithography monopoly, critical semiconductor equipment.",
  "ASTS": "Space-based cellular broadband, direct-to-smartphone satellites.",
  "ATAI": "Clinical-stage biotech, psychedelic therapeutics for mental health.",
  "AWK": "Largest US water and wastewater utility.",
  "AXAHY": "French insurance giant, global financial services.",
  "BBD": "Major Brazilian bank, retail and commercial banking.",
  "BEAM": "Base editing therapeutics, precision genetic medicine.",
  "BG": "Global agricultural processing and commodity trading.",
  "BGNE": "Chinese oncology biotech, global drug development.",
  "BHP": "World's largest mining company, iron ore, copper, nickel.",
  "BLNK": "EV charging equipment and network operator.",
  "BLUE": "Kinase inhibitor drugs for systemic mastocytosis.",
  "BMA": "Argentine bank, retail and commercial financial services.",
  "BNTX": "mRNA technology, COVID vaccine (Pfizer partner), oncology.",
  "BRK-B": "Berkshire Hathaway, Warren Buffett's diversified conglomerate.",
  "BRKS": "Life sciences and semiconductor sample management solutions.",
  "BSAC": "Chilean bank, subsidiary of Santander.",
  "CAMT": "Semiconductor inspection and metrology equipment.",
  "CCJ": "World's largest publicly traded uranium company.",
  "CCL": "Global cruise line operator (Carnival, Princess, Holland America).",
  "CEG": "Nuclear and clean energy utility, largest US nuclear operator.",
  "CF": "Nitrogen fertilizer manufacturer.",
  "CFR": "Texas-based bank, financial services.",
  "CHPT": "EV charging network and equipment provider.",
  "CIB": "Colombian financial group, banking and investment services.",
  "CLSK": "Bitcoin mining company, sustainable operations.",
  "CMPS": "Clinical-stage biotech, psychedelic therapy for depression.",
  "COIN": "Largest US cryptocurrency exchange platform.",
  "CONE": "Data center and digital infrastructure REIT.",
  "COP": "Independent oil and gas exploration and production.",
  "CRSP": "Gene editing therapeutics using CRISPR technology.",
  "CRWD": "Cloud-native cybersecurity, endpoint and threat detection.",
  "CTVA": "Agricultural chemicals and seeds, spun off from DowDuPont.",
  "CYBN": "Clinical-stage biotech, psychedelic therapeutics.",
  "CYBR": "Cybersecurity, privileged access management solutions.",
  "DAVA": "IT services and digital transformation consulting.",
  "DNN": "Uranium mining and exploration in Canada.",
  "DRUG": "Clinical-stage biotech, novel psychoactive therapeutics.",
  "DVA": "Kidney dialysis services, largest US dialysis provider.",
  "DVN": "Oil and gas exploration, Delaware Basin focused.",
  "EA": "Video game publisher (FIFA, Madden, Battlefield, Apex Legends).",
  "EC": "Colombia's state oil company, exploration and production.",
  "EDIT": "Gene editing therapeutics using CRISPR technology.",
  "EMR": "Industrial automation and process control technology.",
  "ENPH": "Solar microinverters and energy management systems.",
  "ENVB": "Clinical-stage biotech, neuroplastogenic therapeutics.",
  "EOG": "Oil and gas exploration, Eagle Ford and Permian focused.",
  "EQNR": "Norwegian energy major, oil, gas, and renewables.",
  "ERJ": "Brazilian aircraft manufacturer, regional and executive jets.",
  "ESRT": "Office and retail REIT, Empire State Building owner.",
  "EVGO": "EV fast charging network operator.",
  "EXPE": "Online travel agency (Expedia, Hotels.com, Vrbo).",
  "FANG": "Permian Basin oil and gas exploration company.",
  "FATE": "Cell therapy, iPSC-derived cellular immunotherapies.",
  "FCX": "World's largest publicly traded copper miner.",
  "FLNC": "Energy storage systems and grid-scale battery solutions.",
  "FMC": "Agricultural chemicals, crop protection products.",
  "FORM": "Semiconductor probe cards and test interface solutions.",
  "FSLR": "Solar panel manufacturer, utility-scale CdTe thin film.",
  "FTNT": "Cybersecurity, next-gen firewall and unified threat management.",
  "FTS": "Canadian electric and gas utility.",
  "GBOOY": "Mexican financial group, banking and insurance.",
  "GD": "Defense contractor, military vehicles, IT, and aerospace.",
  "GEBN.SW": "Swiss sanitary technology, pipes and flushing systems.",
  "GEV": "Energy technology, gas turbines, wind, and grid solutions.",
  "GGB": "Brazilian long steel manufacturer.",
  "GHRS": "Clinical-stage biotech, 5-MeO-DMT for depression.",
  "GLEN": "Global mining and commodities trading giant.",
  "GLOB": "IT services and digital transformation consulting.",
  "GMAB": "Antibody cancer drugs (DuoBody platform), royalties.",
  "GMBXF": "Mexican mining and transportation conglomerate.",
  "GPCR": "Clinical-stage biotech, GPCR-targeted small molecule drugs.",
  "GPN": "Payment processing technology, merchant acquiring.",
  "H": "Global hotel and resort operator.",
  "HESAY": "French luxury goods house, leather, fashion, and accessories.",
  "HLT": "Global hotel chain (Hilton, Hampton, DoubleTree).",
  "HNR1.DE": "Global reinsurance company, Hannover Re.",
  "HRMY": "CNS therapeutics, sleep disorder treatments.",
  "HUT": "Bitcoin mining and digital infrastructure.",
  "IHG.L": "Global hotel group (Holiday Inn, InterContinental, Crowne Plaza).",
  "INFQ": "Quantum technology and cold atom systems.",
  "INFY": "Indian IT services and consulting giant.",
  "IONQ": "Trapped-ion quantum computing company.",
  "IRDM": "Satellite communications, global LEO constellation.",
  "IRM": "Data center and information management, storage REIT.",
  "ISRG": "Robotic-assisted surgery, da Vinci surgical systems.",
  "ITUB": "Latin America's largest bank (Itaú Unibanco).",
  "JKS": "Solar panel manufacturer, global top tier.",
  "KER": "Ukrainian agricultural company, farming and sugar production.",
  "KOF": "World's largest Coca-Cola bottler by volume.",
  "LAC": "Lithium mining, Thacker Pass project in Nevada.",
  "LEGN": "Cell therapy, CAR-T treatment for multiple myeloma.",
  "LEU": "Nuclear fuel supplier, HALEU enrichment for reactors.",
  "LHX": "Defense technology, communications and electronic systems.",
  "LORL": "Satellite communications and space infrastructure.",
  "LVMUY": "World's largest luxury goods group (Louis Vuitton, Dior, Moët).",
  "MAR": "Global hotel chain (Marriott, Ritz-Carlton, St. Regis).",
  "MARA": "Bitcoin mining and digital asset compute.",
  "MAXR": "Satellite imagery and space intelligence solutions.",
  "MELI": "Latin America's largest e-commerce and fintech platform.",
  "MET": "Global insurance and employee benefits company.",
  "MGM": "Casino and entertainment resort operator.",
  "MNMD": "Clinical-stage biotech, psychedelic-inspired therapeutics.",
  "MOS": "Fertilizer company, potash and phosphate products.",
  "MP": "Rare earth mining and processing, Mountain Pass mine.",
  "MPC": "Oil refining and pipeline company.",
  "MRVL": "Semiconductor design, data center and 5G networking chips.",
  "MSTR": "Bitcoin treasury company, largest corporate BTC holder.",
  "MUV2.DE": "World's largest reinsurer, Munich Re.",
  "NCLH": "Cruise line operator (Norwegian, Oceania, Regent).",
  "NNE": "Advanced nuclear energy, microreactor development.",
  "NOC": "Defense contractor, aerospace and missile systems.",
  "NRG": "Power generation and retail electricity provider.",
  "NTDOY": "Japanese gaming giant, creator of Mario, Zelda, and Switch.",
  "NTLA": "Gene editing therapeutics, in-vivo CRISPR treatments.",
  "NTR": "World's largest fertilizer company, potash and nitrogen.",
  "NUMI.TO": "Psychedelic-assisted therapy and mental health clinics.",
  "NVO": "GLP-1 drug leader (Ozempic, Wegovy), diabetes and obesity.",
  "NXE": "Uranium exploration, Arrow deposit in Saskatchewan.",
  "ODDLY.SW": "Swiss-listed company.",
  "OKLO": "Advanced nuclear fission, fast microreactor development.",
  "OKTA": "Identity and access management, enterprise SSO.",
  "PBR": "Brazil's state oil company, deepwater exploration.",
  "PDYN": "AI-driven robotics, autonomous industrial systems.",
  "PEG": "Electric utility serving New Jersey.",
  "PENN.L": "UK water utility company.",
  "POWL": "Electrical equipment, custom power control systems.",
  "PRPL": "Mattress and sleep product manufacturer.",
  "PRU": "Global insurance and financial services company.",
  "PSIL": "Psychedelics and mental health ETF.",
  "PTR": "PetroChina ADR, China's largest oil producer (delisted).",
  "PWSC": "Software and services for public power utilities.",
  "PYPL": "Digital payments platform, online money transfers.",
  "QBTS": "Quantum annealing computing, optimization solutions.",
  "QGEN": "Molecular diagnostics, sample and assay technology.",
  "QLYS": "Cloud-based cybersecurity, vulnerability management.",
  "QNC": "Quantum-safe encryption technology.",
  "QUBT": "Quantum computing software and photonics solutions.",
  "RABO.AS": "Dutch cooperative bank certificates, Rabobank.",
  "RBLX": "Online gaming platform and metaverse for kids and teens.",
  "RBRK": "Cloud data security and cybersecurity backup.",
  "RCL": "Cruise line operator (Royal Caribbean, Celebrity).",
  "RDW": "Space infrastructure, in-space manufacturing and components.",
  "RGTI": "Superconducting quantum computing systems.",
  "RHM.DE": "German defense contractor, military vehicles and munitions.",
  "RIO": "Global mining giant, iron ore, copper, aluminum.",
  "RIOT": "Bitcoin mining and data center infrastructure.",
  "RKLB": "Space launch services, Electron rocket, satellite systems.",
  "RL": "Luxury fashion brand, apparel and accessories.",
  "ROK": "Industrial automation, factory floor control systems.",
  "ROP": "Diversified industrial tech, software and niche hardware.",
  "RUN": "Residential solar and energy storage deployment.",
  "RVLV": "Online fashion retailer, millennial and Gen-Z focused.",
  "SCCO": "World's largest publicly traded copper miner.",
  "SE": "Southeast Asian e-commerce, gaming (Garena), and fintech.",
  "SEDG": "Solar inverters and power optimization systems.",
  "SEEL": "Clinical-stage biotech, CNS therapeutics.",
  "SES": "Lithium-metal battery development for EVs and drones.",
  "SGMO": "Gene therapy, zinc finger protein therapeutics.",
  "SMCI": "Server and AI compute infrastructure manufacturer.",
  "SMR": "Small modular nuclear reactor development.",
  "SNOW": "Cloud data warehouse and AI data platform.",
  "SONY": "Electronics, gaming (PlayStation), entertainment, and sensors.",
  "SQ": "Fintech, payment processing (Square, Cash App, Afterpay).",
  "SQM": "Lithium and specialty chemicals, world's second-largest Li producer.",
  "STNE": "Brazilian fintech, payment processing and banking.",
  "TECK": "Canadian mining, copper, zinc, and steelmaking coal.",
  "TER": "Semiconductor test equipment and automation.",
  "TEVA": "World's largest generic drug manufacturer.",
  "TMQ": "Mineral exploration, copper and zinc in Alaska.",
  "TPR": "Fashion company, Coach and Kate Spade brands.",
  "TRV": "Property and casualty insurance company.",
  "TSM": "World's largest semiconductor foundry.",
  "TTE": "French energy major, oil, gas, LNG, and renewables.",
  "TTWO": "Video game publisher (Grand Theft Auto, Red Dead, NBA 2K).",
  "U": "Game engine and real-time 3D development platform.",
  "UARM": "Under Armour, athletic performance apparel and footwear.",
  "UEC": "Uranium mining and exploration, US-focused.",
  "URA": "ETF tracking global uranium mining companies.",
  "URG": "Uranium mining, Wyoming-based in-situ recovery.",
  "USAR": "Rare earth mining and processing, Texas-based.",
  "UUUU": "Uranium and rare earth mining, White Mesa mill operator.",
  "VALE": "World's largest iron ore and nickel miner.",
  "VE": "VanEck ETF or data-quality-related instrument.",
  "VEEV": "Life sciences cloud software, CRM for pharma.",
  "VIAV": "Network testing, monitoring, and fiber optic components.",
  "VIV": "Brazilian telecom operator (Telefônica Brasil).",
  "VKTX": "GLP-1 drug development, oral obesity treatments.",
  "VNET": "Chinese data center and cloud services provider.",
  "VRTX": "Cystic fibrosis leader, expanding into pain and gene editing.",
  "VST": "Power generation and retail electricity, Texas-focused.",
  "VTRS": "Global generic and branded pharmaceutical company.",
  "WBX": "EV charging station manufacturer, residential and commercial.",
  "WIT": "Indian IT services, consulting, and digital transformation.",
  "WMMVY": "Mexico's largest retailer, Walmart subsidiary.",
  "WTRG": "Water and wastewater utility serving US states.",
  "XNDU": "Photonic quantum computing hardware and software.",
  "XYL": "Water technology, pumps, treatment, and analytics.",
  "YPF": "Argentina's state energy company, oil and gas.",
  "ZLAB": "Chinese biotech, oncology and autoimmune drug development.",
  "ZS": "Cloud cybersecurity, zero-trust network access.",
  "ZURVY": "Swiss insurance group, global property and casualty.",
};

async function main() {
  let updated = 0;
  let skipped = 0;

  for (const [ticker, desc] of Object.entries(descriptions)) {
    try {
      const result = await db.execute({
        sql: "UPDATE watchlist_scores SET description = ? WHERE ticker = ?",
        args: [desc, ticker],
      });
      if (result.rowsAffected > 0) {
        updated++;
      } else {
        skipped++;
      }
    } catch (e) {
      console.error("Error updating " + ticker + ":", e);
    }
  }

  console.log("Updated " + updated + " tickers with descriptions.");
  console.log("Skipped " + skipped + " (not found in DB).");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
