import { createClient } from "@libsql/client";
import * as dotenv from "dotenv";

dotenv.config({ path: ".env.local" });

const db = createClient({
  url: process.env.TURSO_DATABASE_URL!,
  authToken: process.env.TURSO_AUTH_TOKEN,
});

const descriptions: Record<string, string> = {
  "AGCO": "Agricultural equipment manufacturer (tractors, combines).",
  "AIG": "Global insurance company, property and casualty.",
  "ALLG": "Allegro MicroSystems, power and sensor ICs for automotive.",
  "ALV.DE": "Global insurance and asset management giant.",
  "AMT": "Cell tower REIT, wireless infrastructure landlord globally.",
  "AMX": "Latin America's largest telecom operator.",
  "ANTM.JK": "Indonesian state-owned mining, nickel and precious metals.",
  "ANTO.L": "Chilean copper mining company listed in London.",
  "ASML": "EUV lithography monopoly, critical semiconductor equipment.",
  "ASTS": "Space-based cellular broadband, direct-to-smartphone satellites.",
  "ATAI": "Clinical-stage biotech, psychedelic therapeutics for mental health.",
  "AWK": "Largest US water and wastewater utility.",
  "AXAHY": "French insurance giant, global financial services.",
  "BBD": "Major Brazilian bank, retail and commercial banking.",
  "BEAM": "Base editing therapeutics, precision genetic medicine.",
  "BG": "Global agricultural processing and commodity trading.",
  "BGNE": "Chinese oncology biotech, global drug development.",
  "BHP": "World's largest mining company, iron ore, copper, nickel.",
  "BLNK": "EV charging equipment and network operator.",
  "BLUE": "Kinase inhibitor drugs for systemic mastocytosis.",
  "BMA": "Argentine bank, retail and commercial financial services.",
  "BNTX": "mRNA technology, COVID vaccine (Pfizer partner), oncology.",
  "BRK-B": "Berkshire Hathaway, Warren Buffett's diversified conglomerate.",
  "BRKS": "Life sciences and semiconductor sample management solutions.",
  "BRPT.JK": "Indonesian conglomerate, petrochemicals and energy.",
  "BSAC": "Chilean bank, subsidiary of Santander.",
  "CAMT": "Semiconductor inspection and metrology equipment.",
  "CCJ": "World's largest publicly traded uranium company.",
  "CCL": "Global cruise line operator (Carnival, Princess, Holland America).",
  "CEG": "Nuclear and clean energy utility, largest US nuclear operator.",
  "CF": "Nitrogen fertilizer manufacturer.",
  "CFR": "Texas-based bank, financial services.",
  "CHPT": "EV charging network and equipment provider.",
  "CIB": "Colombian financial group, banking and investment services.",
  "CLSK": "Bitcoin mining company, sustainable operations.",
  "CMPS": "Clinical-stage biotech, psychedelic therapy for depression.",
  "COIN": "Largest US cryptocurrency exchange platform.",
  "CONE": "Data center and digital infrastructure REIT.",
  "COP": "Independent oil and gas exploration and production.",
  "CRSP": "Gene editing therapeutics using CRISPR technology.",
  "CRWD": "Cloud-native cybersecurity, endpoint and threat detection.",
  "CTVA": "Agricultural chemicals and seeds, spun off from DowDuPont.",
  "CYBN": "Clinical-stage biotech, psychedelic therapeutics.",
  "CYBR": "Cybersecurity, privileged access management solutions.",
  "DAVA": "IT services and digital transformation consulting.",
  "DNN": "Uranium mining and exploration in Canada.",
  "DRUG": "Clinical-stage biotech, novel psychoactive therapeutics.",
  "DVA": "Kidney dialysis services, largest US dialysis provider.",
  "DVN": "Oil and gas exploration, Delaware Basin focused.",
  "EA": "Video game publisher (FIFA, Madden, Battlefield, Apex Legends).",
  "EC": "Colombia's state oil company, exploration and production.",
  "EDIT": "Gene editing therapeutics using CRISPR technology.",
  "EMR": "Industrial automation and process control technology.",
  "ENPH": "Solar microinverters and energy management systems.",
  "ENVB": "Clinical-stage biotech, neuroplastogenic therapeutics.",
  "EOG": "Oil and gas exploration, Eagle Ford and Permian focused.",
  "EQNR": "Norwegian energy major, oil, gas, and renewables.",
  "ERAA.JK": "Indonesian mobile device distributor and retailer.",
  "ERJ": "Brazilian aircraft manufacturer, regional and executive jets.",
  "ESRT": "Office and retail REIT, Empire State Building owner.",
  "EVGO": "EV fast charging network operator.",
  "EXPE": "Online travel agency (Expedia, Hotels.com, Vrbo).",
  "FANG": "Permian Basin oil and gas exploration company.",
  "FATE": "Cell therapy, iPSC-derived cellular immunotherapies.",
  "FCX": "World's largest publicly traded copper miner.",
  "FLNC": "Energy storage systems and grid-scale battery solutions.",
  "FMC": "Agricultural chemicals, crop protection products.",
  "FORM": "Semiconductor probe cards and test interface solutions.",
  "FSLR": "Solar panel manufacturer, utility-scale CdTe thin film.",
  "FTNT": "Cybersecurity, next-gen firewall and unified threat management.",
  "FTS": "Canadian electric and gas utility.",
  "GBOOY": "Mexican financial group, banking and insurance.",
  "GD": "Defense contractor, military vehicles, IT, and aerospace.",
  "GEBN.SW": "Swiss sanitary technology, pipes and flushing systems.",
  "GEV": "Energy technology, gas turbines, wind, and grid solutions.",
  "GGB": "Brazilian long steel manufacturer.",
  "GHRS": "Clinical-stage biotech, 5-MeO-DMT for depression.",
  "GLEN": "Global mining and commodities trading giant.",
  "GLOB": "IT services and digital transformation consulting.",
  "GMAB": "Antibody cancer drugs (DuoBody platform), royalties.",
  "GMBXF": "Mexican mining and transportation conglomerate.",
  "GPCR": "Clinical-stage biotech, GPCR-targeted small molecule drugs.",
  "GPN": "Payment processing technology, merchant acquiring.",
  "H": "Global hotel and resort operator.",
  "HESAY": "French luxury goods house, leather, fashion, and accessories.",
  "HLT": "Global hotel chain (Hilton, Hampton, DoubleTree).",
  "HMSP.JK": "Indonesian tobacco company, Philip Morris subsidiary.",
  "HNR1.DE": "Global reinsurance company, Hannover Re.",
  "HRMY": "CNS therapeutics, sleep disorder treatments.",
  "HUT": "Bitcoin mining and digital infrastructure.",
  "ICICIBANK.NS": "Major Indian private sector bank.",
  "IHG.L": "Global hotel group (Holiday Inn, InterContinental, Crowne Plaza).",
  "INCO.JK": "Indonesian nickel mining company.",
  "INFQ": "Quantum technology and cold atom systems.",
  "INFY": "Indian IT services and consulting giant.",
  "IONQ": "Trapped-ion quantum computing company.",
  "IRDM": "Satellite communications, global LEO constellation.",
  "IRM": "Data center and information management, storage REIT.",
  "ISRG": "Robotic-assisted surgery, da Vinci surgical systems.",
  "ITUB": "Latin America's largest bank (Itaú Unibanco).",
  "JKS": "Solar panel manufacturer, global top tier.",
  "KER": "Ukrainian agricultural company, farming and sugar production.",
  "KOF": "World's largest Coca-Cola bottler by volume.",
  "LAC": "Lithium mining, Thacker Pass project in Nevada.",
  "LEGN": "Cell therapy, CAR-T treatment for multiple myeloma.",
  "LEU": "Nuclear fuel supplier, HALEU enrichment for reactors.",
  "LHX": "Defense technology, communications and electronic systems.",
  "LORL": "Satellite communications and space infrastructure.",
  "LT.NS": "Indian engineering, construction, and defense conglomerate.",
  "LVMUY": "World's largest luxury goods group (Louis Vuitton, Dior, Moët).",
  "MAR": "Global hotel chain (Marriott, Ritz-Carlton, St. Regis).",
};

async function main() {
  let updated = 0;
  for (const [ticker, desc] of Object.entries(descriptions)) {
    const result = await db.execute({
      sql: "UPDATE watchlist_scores SET description = ? WHERE ticker = ?",
      args: [desc, ticker],
    });
    if (result.rowsAffected > 0) updated++;
  }
  console.log("Updated " + updated + " tickers with descriptions (batch 3).");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
