import { createClient } from "@libsql/client";
import * as dotenv from "dotenv";

dotenv.config({ path: ".env.local" });

const db = createClient({
  url: process.env.TURSO_DATABASE_URL!,
  authToken: process.env.TURSO_AUTH_TOKEN,
});

const descriptions: Record<string, string> = {
  "3483.T": "Japanese listed company on Tokyo Stock Exchange.",
  "4063.T": "Chemical company, world's largest silicon wafer and PVC producer.",
  "4502.T": "Japan's largest pharmaceutical company with global operations.",
  "4503.T": "Japanese pharmaceutical company, oncology and urology drugs.",
  "4519.T": "Japanese biotech (Roche subsidiary), antibody drug innovation.",
  "4565.T": "Japanese biotech, CNS and neurology drug development.",
  "4568.T": "Japanese pharma, oncology (Enhertu with AstraZeneca partnership).",
  "4578.T": "Japanese pharmaceutical company, CNS and cardiovascular drugs.",
  "4587.T": "Peptide drug discovery platform and therapeutics.",
  "4592.T": "Regenerative medicine and stem cell therapy development.",
  "4661.T": "Operator of Tokyo Disney Resort theme parks.",
  "5713.T": "Non-ferrous metals mining, copper, nickel, and gold.",
  "6108.T": "Japanese listed company on Tokyo Stock Exchange.",
  "6302.T": "Industrial machinery, semiconductor and precision equipment.",
  "6501.T": "Japanese industrial conglomerate, IT, energy, and infrastructure.",
  "6702.T": "Japanese IT services, computing, and digital transformation.",
  "6861.T": "Factory automation sensors and measurement equipment, high margins.",
  "6954.T": "Industrial robots, CNC systems, and factory automation leader.",
  "7203.T": "World's largest automaker, hybrid and hydrogen vehicle leader.",
  "7735.T": "Semiconductor cleaning and coating equipment manufacturer.",
  "7974.T": "Japanese gaming giant, creator of Mario, Zelda, and Switch.",
  "8001.T": "Japanese trading house (sogo shosha), diversified global investments.",
  "8002.T": "Japanese trading house, diversified investments and commodities.",
  "8031.T": "Japanese trading house, global resources, energy, and finance.",
  "8035.T": "Semiconductor manufacturing equipment global leader.",
  "8053.T": "Japanese trading house, mineral resources and infrastructure.",
  "8058.T": "Japan's largest trading house, diversified global conglomerate.",
  "8306.T": "Japan's largest bank and financial services group.",
  "8316.T": "Japan's second-largest banking and financial services group.",
  "8411.T": "Major Japanese banking and financial services group.",
  "8630.T": "Japanese property and casualty insurance company.",
  "8634.T": "Japanese financial services company listed on TSE.",
  "8725.T": "Japanese insurance holding company, P&C and life insurance.",
  "8766.T": "Japan's largest property and casualty insurance company.",
  "9109.T": "Japanese maritime and shipping services company.",
  "9201.T": "Japan's flag carrier airline.",
  "9202.T": "Japan's largest airline group (ANA).",
  "9433.T": "Japanese telecom operator, mobile and broadband (au brand).",
  "9682.T": "IT services, system integration, and consulting.",
  "9697.T": "Video game developer (Street Fighter, Resident Evil, Monster Hunter).",
  "9783.T": "Japanese listed company on Tokyo Stock Exchange.",
  "000660.KS": "World's second-largest memory chip maker (DRAM, NAND).",
  "003490.KS": "Korean Air Lines, South Korea's flag carrier airline.",
  "005380.KS": "South Korea's largest automaker (Hyundai Motor Group).",
  "005930.KS": "World's largest memory chip and smartphone maker.",
  "006400.KS": "Battery manufacturer, EV and energy storage systems.",
  "008770.KS": "Hotel Shilla, duty-free retail and hotel operations.",
  "012450.KS": "Aerospace and defense, satellite and missile systems.",
  "032830.KS": "South Korea's largest life insurance company.",
  "035420.KS": "South Korea's leading search engine and internet platform.",
  "036570.KS": "Online and mobile gaming company (Lineage, Aion).",
  "036930.KS": "Korean listed company on KOSPI.",
  "042700.KQ": "Korean listed company on KOSDAQ.",
  "051910.KS": "Chemicals, EV batteries, and advanced materials.",
  "051915.KS": "LG Chem preferred shares.",
  "056080.KQ": "Robot and automated guided vehicle (AGV) manufacturer.",
  "066570.KS": "Consumer electronics, TVs, home appliances, and EV components.",
  "088350.KS": "South Korean life insurance and financial services.",
  "207940.KS": "Biologics CDMO, antibody drug contract manufacturing.",
  "259960.KQ": "Korean listed company on KOSDAQ.",
  "277810.KQ": "Humanoid and collaborative robot manufacturer.",
  "348340.KQ": "Industrial robotics and factory automation systems.",
  "373220.KQ": "Korean listed company on KOSDAQ.",
  "5E2.SI": "Offshore marine engineering (formerly Sembcorp Marine).",
  "AJBU.SI": "Data center REIT across Asia-Pacific.",
  "BN4.SI": "Diversified conglomerate, offshore energy and property development.",
  "C6L.SI": "Singapore Airlines, Singapore's flag carrier.",
  "C7BU.SI": "Singapore-listed company on SGX.",
  "D05.SI": "Southeast Asia's largest bank.",
  "D5IU.SI": "Singapore REIT, retail and commercial properties.",
  "E5H.SI": "Palm oil plantation company, one of the world's largest.",
  "F34.SI": "Agribusiness, palm oil and food processing conglomerate.",
  "F9D.SI": "Engineering and geospatial technology services.",
  "G07.SI": "Insurance company, Southeast Asia's largest life insurer.",
  "G13.SI": "Gaming and hospitality (Resorts World Sentosa).",
  "N2IU.SI": "Pan-Asia commercial REIT, office and retail properties.",
  "P40U.SI": "Retail and hospitality REIT across Asia.",
  "Q0F.SI": "Healthcare, hospital operator (Parkway, Gleneagles, Acibadem).",
  "S63.SI": "Defense, aerospace, and smart city technology.",
  "T68U.SI": "Singapore-listed REIT on SGX.",
  "VC2.SI": "Agricultural commodity trading and food ingredients.",
  "Z74.SI": "Singapore's largest telecom operator.",
  "2330.TW": "World's largest semiconductor foundry (TSMC).",
  "3529.TWO": "Memory IP and security technology for semiconductors.",
  "4971.TWO": "EPI wafer and semiconductor materials.",
  "500325.NS": "Indian listed company on NSE (numeric ticker code).",
  "532500.NS": "Indian listed company on NSE (numeric ticker code).",
  "HDFCBANK.NS": "India's largest private sector bank.",
  "HINDUNILVR.NS": "Indian FMCG giant, subsidiary of Unilever.",
  "ICICIBANK.NS": "Major Indian private sector bank.",
  "LT.NS": "Indian engineering and construction conglomerate.",
  "RELIANCE.NS": "India's largest conglomerate: energy, retail, telecom (Jio).",
  "SBIN.NS": "India's largest bank, government-owned.",
  "TATAMOTORS.NS": "India's largest automaker, owns Jaguar Land Rover.",
  "TCS.NS": "India's largest IT services company.",
  "ANTM.JK": "Indonesian state mining company, nickel and gold.",
  "BRPT.JK": "Indonesian conglomerate, energy and property.",
  "ERAA.JK": "Indonesian mobile phone distributor and retailer.",
  "HMSP.JK": "Indonesian tobacco company (PMI subsidiary).",
  "INCO.JK": "Nickel mining company (Vale subsidiary).",
  "MDKA.JK": "Indonesian mining company, copper and gold.",
  "NIKL.JK": "Tin smelting and metal processing.",
  "PTRO.JK": "Mining services and civil construction.",
  "SMSM.JK": "Automotive filters and parts manufacturer.",
  "TPIA.JK": "Petrochemical company, olefins and plastics.",
  "ABEV": "Latin America's largest brewer (Ambev/AB InBev subsidiary).",
  "ABNB": "Global online marketplace for short-term lodging and experiences.",
  "ADM": "Global agricultural processing and commodity trading.",
  "ADYEY": "European payment processor, global fintech platform.",
  "AFL": "Supplemental insurance, cancer and life policies.",
  "AFRM": "Buy-now-pay-later fintech platform.",
};

async function main() {
  let updated = 0;
  for (const [ticker, desc] of Object.entries(descriptions)) {
    const result = await db.execute({
      sql: "UPDATE watchlist_scores SET description = ? WHERE ticker = ?",
      args: [desc, ticker],
    });
    if (result.rowsAffected > 0) updated++;
  }
  console.log("Updated " + updated + " tickers with descriptions (batch 2).");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
