import { createClient } from "@libsql/client";
import * as dotenv from "dotenv";

dotenv.config({ path: ".env.local" });

const db = createClient({
  url: process.env.TURSO_DATABASE_URL!,
  authToken: process.env.TURSO_AUTH_TOKEN,
});

const descriptions: Record<string, string> = {
  "MARA": "Bitcoin mining and digital asset compute.",
  "MAXR": "Satellite imagery and space intelligence solutions.",
  "MDKA.JK": "Indonesian mining, copper and gold exploration.",
  "MELI": "Latin America's largest e-commerce and fintech platform.",
  "MET": "Global insurance and employee benefits company.",
  "MGM": "Casino and entertainment resort operator.",
  "MNMD": "Clinical-stage biotech, psychedelic-inspired therapeutics.",
  "MOS": "Fertilizer company, potash and phosphate products.",
  "MP": "Rare earth mining and processing, Mountain Pass mine.",
  "MPC": "Oil refining and pipeline company.",
  "MRVL": "Semiconductor design, data center and 5G networking chips.",
  "MSTR": "Bitcoin treasury company, largest corporate BTC holder.",
  "MUV2.DE": "World's largest reinsurer, Munich Re.",
  "NCLH": "Cruise line operator (Norwegian, Oceania, Regent).",
  "NIKL.JK": "Indonesian tin smelting and processing company.",
  "NNE": "Advanced nuclear energy, microreactor development.",
  "NOC": "Defense contractor, aerospace and missile systems.",
  "NRG": "Power generation and retail electricity provider.",
  "NTDOY": "Japanese gaming giant, creator of Mario, Zelda, and Switch.",
  "NTLA": "Gene editing therapeutics, in-vivo CRISPR treatments.",
  "NTR": "World's largest fertilizer company, potash and nitrogen.",
  "NUMI.TO": "Psychedelic-assisted therapy and mental health clinics.",
  "NVO": "GLP-1 drug leader (Ozempic, Wegovy), diabetes and obesity.",
  "NXE": "Uranium exploration, Arrow deposit in Saskatchewan.",
  "ODDLY.SW": "Swiss-listed company.",
  "OKLO": "Advanced nuclear fission, fast microreactor development.",
  "OKTA": "Identity and access management, enterprise SSO.",
  "PBR": "Brazil's state oil company, deepwater exploration.",
  "PDYN": "AI-driven robotics, autonomous industrial systems.",
  "PEG": "Electric utility serving New Jersey.",
  "PENN.L": "UK water utility company.",
  "POWL": "Electrical equipment, custom power control systems.",
  "PRPL": "Mattress and sleep product manufacturer.",
  "PRU": "Global insurance and financial services company.",
  "PSIL": "Psychedelics and mental health ETF.",
  "PTR": "PetroChina ADR, China's largest oil producer (delisted).",
  "PTRO.JK": "Indonesian mining services and civil construction.",
  "PWSC": "Software and services for public power utilities.",
  "PYPL": "Digital payments platform, online money transfers.",
  "QBTS": "Quantum annealing computing, optimization solutions.",
  "QGEN": "Molecular diagnostics, sample and assay technology.",
  "QLYS": "Cloud-based cybersecurity, vulnerability management.",
  "QNC": "Quantum-safe encryption technology.",
  "QUBT": "Quantum computing software and photonics solutions.",
  "RABO.AS": "Dutch cooperative bank certificates, Rabobank.",
  "RBLX": "Online gaming platform and metaverse for kids and teens.",
  "RBRK": "Cloud data security and cybersecurity backup.",
  "RCL": "Cruise line operator (Royal Caribbean, Celebrity).",
  "RDW": "Space infrastructure, in-space manufacturing and components.",
  "RELIANCE.NS": "India's largest conglomerate: energy, retail, telecom.",
  "RGTI": "Superconducting quantum computing systems.",
  "RHM.DE": "German defense contractor, military vehicles and munitions.",
  "RIO": "Global mining giant, iron ore, copper, aluminum.",
  "RIOT": "Bitcoin mining and data center infrastructure.",
  "RKLB": "Space launch services, Electron rocket, satellite systems.",
  "RL": "Luxury fashion brand, apparel and accessories.",
  "ROK": "Industrial automation, factory floor control systems.",
  "ROP": "Diversified industrial tech, software and niche hardware.",
  "RUN": "Residential solar and energy storage deployment.",
  "RVLV": "Online fashion retailer, millennial and Gen-Z focused.",
  "SBIN.NS": "State Bank of India, largest government-owned bank.",
  "SCCO": "World's largest publicly traded copper miner.",
  "SE": "Southeast Asian e-commerce, gaming (Garena), and fintech.",
  "SEDG": "Solar inverters and power optimization systems.",
  "SEEL": "Clinical-stage biotech, CNS therapeutics.",
  "SES": "Lithium-metal battery development for EVs and drones.",
  "SGMO": "Gene therapy, zinc finger protein therapeutics.",
  "SMCI": "Server and AI compute infrastructure manufacturer.",
  "SMR": "Small modular nuclear reactor development.",
  "SMSM.JK": "Indonesian automotive parts, filters and components.",
  "SNOW": "Cloud data warehouse and AI data platform.",
  "SONY": "Electronics, gaming (PlayStation), entertainment, and sensors.",
  "SQ": "Fintech, payment processing (Square, Cash App, Afterpay).",
  "SQM": "Lithium and specialty chemicals, world's second-largest Li producer.",
  "STNE": "Brazilian fintech, payment processing and banking.",
  "TATAMOTORS.NS": "India's largest automaker, owns Jaguar Land Rover.",
  "TCS.NS": "India's largest IT services company (Tata Consultancy).",
  "TECK": "Canadian mining, copper, zinc, and steelmaking coal.",
  "TER": "Semiconductor test equipment and automation.",
  "TEVA": "World's largest generic drug manufacturer.",
  "TMQ": "Mineral exploration, copper and zinc in Alaska.",
  "TPIA.JK": "Indonesian petrochemical company, olefins and polyethylene.",
  "TPR": "Fashion company, Coach and Kate Spade brands.",
  "TRV": "Property and casualty insurance company.",
  "TSM": "World's largest semiconductor foundry.",
  "TTE": "French energy major, oil, gas, LNG, and renewables.",
  "TTWO": "Video game publisher (Grand Theft Auto, Red Dead, NBA 2K).",
  "U": "Game engine and real-time 3D development platform.",
  "UARM": "Under Armour, athletic performance apparel and footwear.",
  "UEC": "Uranium mining and exploration, US-focused.",
  "URA": "ETF tracking global uranium mining companies.",
  "URG": "Uranium mining, Wyoming-based in-situ recovery.",
  "USAR": "Rare earth mining and processing, Texas-based.",
  "UUUU": "Uranium and rare earth mining, White Mesa mill operator.",
  "VALE": "World's largest iron ore and nickel miner.",
  "VE": "VanEck ETF or data-quality-related instrument.",
  "VEEV": "Life sciences cloud software, CRM for pharma.",
  "VIAV": "Network testing, monitoring, and fiber optic components.",
  "VIV": "Brazilian telecom operator (Telefônica Brasil).",
  "VKTX": "GLP-1 drug development, oral obesity treatments.",
  "VNET": "Chinese data center and cloud services provider.",
  "VRTX": "Cystic fibrosis leader, expanding into pain and gene editing.",
  "VST": "Power generation and retail electricity, Texas-focused.",
  "VTRS": "Global generic and branded pharmaceutical company.",
  "WBX": "EV charging station manufacturer, residential and commercial.",
  "WIT": "Indian IT services, consulting, and digital transformation.",
  "WMMVY": "Mexico's largest retailer, Walmart subsidiary.",
  "WTRG": "Water and wastewater utility serving US states.",
  "XNDU": "Photonic quantum computing hardware and software.",
  "XYL": "Water technology, pumps, treatment, and analytics.",
  "YPF": "Argentina's state energy company, oil and gas.",
  "ZLAB": "Chinese biotech, oncology and autoimmune drug development.",
  "ZS": "Cloud cybersecurity, zero-trust network access.",
  "ZURVY": "Swiss insurance group, global property and casualty.",
};

async function main() {
  let updated = 0;
  for (const [ticker, desc] of Object.entries(descriptions)) {
    const result = await db.execute({
      sql: "UPDATE watchlist_scores SET description = ? WHERE ticker = ?",
      args: [desc, ticker],
    });
    if (result.rowsAffected > 0) updated++;
  }
  console.log("Updated " + updated + " tickers with descriptions (batch 4).");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
