import { createClient } from "@libsql/client";
import * as dotenv from "dotenv";

dotenv.config({ path: ".env.local" });

const db = createClient({
  url: process.env.TURSO_DATABASE_URL!,
  authToken: process.env.TURSO_AUTH_TOKEN,
});

// Top 100 US tickers with 1-liner descriptions
const descriptions: Record<string, string> = {
  "AAPL": "Consumer electronics, software, and services giant.",
  "MSFT": "Cloud computing, productivity software, and AI platform.",
  "GOOGL": "Search, advertising, cloud, and AI technology leader.",
  "AMZN": "E-commerce, cloud computing (AWS), and logistics.",
  "NVDA": "GPU and AI accelerator chip design, data center compute.",
  "TSLA": "Electric vehicles, energy storage, and autonomous driving.",
  "META": "Social media platforms, VR/AR, and AI infrastructure.",
  "JPM": "Global investment bank and consumer financial services.",
  "V": "Global payment network and fintech infrastructure.",
  "WMT": "Retail giant, grocery, e-commerce, and logistics.",
  "JNJ": "Pharmaceuticals, medical devices, and consumer health.",
  "UNH": "Managed healthcare, insurance, and Optum services.",
  "XOM": "Integrated oil and gas exploration, production, refining.",
  "LLY": "Pharmaceuticals, GLP-1 drugs (Mounjaro/Zepbound).",
  "MA": "Global payment network and digital transaction services.",
  "PG": "Consumer packaged goods, household and personal care brands.",
  "HD": "Home improvement retail, tools, appliances, pro services.",
  "CVX": "Integrated oil and gas, upstream and downstream operations.",
  "MRK": "Pharmaceuticals, vaccines, oncology, and animal health.",
  "KO": "Non-alcoholic beverages, sparkling and still drinks.",
  "PEP": "Snacks and beverages, Frito-Lay and Pepsi brands.",
  "BAC": "Consumer banking, wealth management, investment banking.",
  "ABBV": "Pharmaceuticals, immunology, oncology, and aesthetics.",
  "AVGO": "Semiconductor design, networking, and software infrastructure.",
  "PFE": "Pharmaceuticals, vaccines, oncology, and primary care.",
  "TMO": "Scientific instruments, life sciences, and diagnostics.",
  "COST": "Membership warehouse retail, bulk goods, and services.",
  "DIS": "Media, entertainment, theme parks, and streaming (Disney+).",
  "ADBE": "Creative software, document cloud, and marketing platforms.",
  "NFLX": "Streaming entertainment, original content production.",
  "CRM": "Enterprise cloud software, CRM, and AI (Einstein).",
  "ACN": "Management consulting, technology services, and outsourcing.",
  "VZ": "Wireless telecom, broadband, and media services.",
  "TXN": "Analog and embedded semiconductor chips for industrial.",
  "NEE": "Renewable energy utility, wind, solar, and nuclear.",
  "BMY": "Pharmaceuticals, oncology, immunology, and cardiovascular.",
  "RTX": "Aerospace, defense, and intelligence technology.",
  "HON": "Industrial conglomerate, aerospace, building technologies.",
  "QCOM": "Wireless semiconductor, 5G modems, and IoT connectivity.",
  "AMGN": "Biotechnology, human therapeutics, and biosimilars.",
  "CAT": "Construction and mining equipment, engines, and services.",
  "IBM": "Hybrid cloud, AI (Watson), and enterprise consulting.",
  "GE": "Aerospace engines, renewable energy, and grid technology.",
  "SBUX": "Global coffeehouse chain, retail and licensed stores.",
  "AMD": "CPU and GPU semiconductor design for PC and data center.",
  "NOW": "Enterprise cloud workflow platform, IT service management.",
  "INTC": "CPU and semiconductor manufacturing for PC and data center.",
  "SPGI": "Financial ratings, benchmarks, and market intelligence.",
  "GILD": "Biotechnology, antivirals, oncology, and cell therapy.",
  "PLD": "Industrial REIT, logistics warehouses, and distribution.",
  "UPS": "Global package delivery, logistics, and supply chain.",
  "LOW": "Home improvement retail, appliances, and pro services.",
  "T": "Wireless telecom, broadband, and media (Warner Bros).",
  "MDT": "Medical devices, diabetes, cardiovascular, and surgical.",
  "DHR": "Life sciences, diagnostics, and biotechnology tools.",
  "LMT": "Aerospace, defense, and advanced technology systems.",
  "CI": "Managed healthcare, pharmacy benefits, and insurance.",
  "DE": "Agricultural machinery, construction, and precision farming.",
  "SYK": "Medical devices, orthopedics, and surgical equipment.",
  "CB": "Global property and casualty insurance, reinsurance.",
  "AXP": "Charge and credit card network, travel, and banking.",
  "MS": "Investment bank, wealth management, and trading.",
  "NKE": "Athletic footwear, apparel, and equipment globally.",
  "GS": "Investment banking, securities, and asset management.",
  "SCHW": "Brokerage, wealth management, and banking services.",
  "PGR": "Personal auto insurance, property and casualty.",
  "C": "Global banking, consumer lending, and institutional services.",
  "BLK": "Asset management, ETFs (iShares), and risk analytics.",
  "BKNG": "Online travel agency, hotels, flights, and rental cars.",
  "MDLZ": "Snacks and confectionery, Mondelez global brands.",
  "AMAT": "Semiconductor manufacturing equipment and materials.",
  "ADI": "Analog, mixed-signal, and digital signal processing chips.",
  "REGN": "Biotechnology, monoclonal antibodies, and genetics.",
  "LRCX": "Semiconductor wafer processing equipment and services.",
  "KLAC": "Process control and yield management for semiconductors.",
  "PANW": "Enterprise cybersecurity, firewalls, and cloud security.",
  "SNPS": "Electronic design automation (EDA) software for chips.",
  "TMUS": "Wireless telecom, 5G network, and consumer services.",
  "ETN": "Power management, electrical components, and aerospace.",
  "SO": "Electric utility, generation, transmission, and distribution.",
  "DUK": "Electric utility, generation, transmission, and distribution.",
  "APD": "Industrial gases, chemicals, and energy transition.",
  "SHW": "Paints, coatings, and specialty materials globally.",
  "ITW": "Industrial manufacturing, automotive, and food equipment.",
  "EL": "Prestige beauty, skincare, and fragrance products.",
  "HCA": "Hospital operations, healthcare facilities, and ER.",
  "FDX": "Global express delivery, e-commerce logistics, and freight.",
  "MU": "Memory and storage semiconductor chips (DRAM, NAND).",
  "CME": "Financial derivatives exchange, futures, and options.",
  "ICE": "Exchange operator, data, and mortgage technology.",
  "AON": "Professional services, risk, reinsurance, and retirement.",
  "MMC": "Insurance broker, risk advisory, and consulting.",
  "PSA": "Self-storage REIT, real estate investment trust.",
  "O": "Net lease REIT, commercial properties, monthly dividend.",
  "CCI": "Cell tower REIT, wireless infrastructure landlord.",
  "EQIX": "Data center REIT, interconnection, and colocation.",
  "DLR": "Data center REIT, cloud and carrier-neutral facilities.",
  "WELL": "Healthcare REIT, senior housing, and medical offices.",
  "VTR": "Healthcare REIT, senior living, and medical office.",
  "SPG": "Mall REIT, premium shopping centers, and outlets.",
  "AVB": "Apartment REIT, multifamily residential properties.",
  "EQR": "Apartment REIT, urban and suburban residential.",
  "UDR": "Apartment REIT, diversified residential communities.",
  "AIV": "Apartment REIT, Sun Belt residential properties.",
  "EXR": "Self-storage REIT, acquisition and development.",
  "BXP": "Office REIT, Boston, SF, LA, and Seattle properties.",
  "ARE": "Life science REIT, lab and office for biotech.",
  "HST": "Hotel REIT, upscale and luxury lodging.",
};

async function main() {
  let updated = 0;
  for (const [ticker, desc] of Object.entries(descriptions)) {
    const result = await db.execute({
      sql: "UPDATE watchlist_scores SET description = ? WHERE ticker = ?",
      args: [desc, ticker],
    });
    if (result.rowsAffected > 0) updated++;
  }
  console.log(`Updated ${updated} tickers with descriptions.`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
